name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip configuraiton files
        run: zip -r PrusaSlicer-AMCE-Profile.zip vendor

      - name: Zip add install files
        run: zip -u PrusaSlicer-AMCE-Profile.zip install.ps1 install.sh AMCE_config_bundle.ini

      - name: Upload GitHub release assets
        uses: vesoft-inc/upload-assets@v1.0.0
        with:
          asset-path: ./PrusaSlicer-AMCE-Profile.zip
          tag: ${{ inputs.tag }}

      - name: Remove Zip configuraiton files
        run: rm PrusaSlicer-AMCE-Profile.zip
