name: Publish

on:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip-Release4cpp
        uses: darshitsri/zip-release@v3
        with:
        # Filename for archive
          filename: PrusaSlicer-AMCE-Profile.zip
          exclusions: .\.github\.*, \.git.* , CODEOWNERS, LICENCE, changelog.md, readme.md
